### ISSUE TITLE
Default decoding on `parse` results

### ISSUE THREAD

**Issue by silverbullettruck2001** [lib-ruby-parser/node-bindings#5]
Within the `ast.statements[]` array, there is an array property called `args`.  The elements in that array are returned as `Uint8Array` types.  Is it possible to have these returned using the same decoder that is specified (or using UTF8/ASCII if none is provided)?   The same thing goes for the `ast.statements[].call` and `ast.statements[].body.statements[].value` which also has an `args` array property.

**Comment by iliabylich** [comment]
If it's a `Uint8Array` then it's a byte array of UTF-8 characters. If encoding of the input is different from UTF-8/ASCII (but set with a special magic encoding comment) it can be re-encoded with a `decoder` argument. Technically it's not guaranteed that it's a valid UTF-8 string, that's why it's returned as a byte array:

```ruby
# encoding: utf-8
"\xFF"
```

^ this is a trivial example of invalid string. In this case you'll get an array of `[255]` (which is invalid in UTF-8).

So these byte arrays use `decoder` internally to convert input to UTF-8 and then parse these strings. Also, I'm not sure what is `ast.statements[].args`. Are you using TS? If so you probably mean something like `nodes.String.prototype.value` or something similar (if you don't use TS you definitely should. The structure of the AST is fully defined in TS types, at least check `types.d.ts` in your local instlalation).

I think you can do `new TextDecoder().decode(uint8Array)` to convert it to string:

```js
> new TextDecoder().decode(new Uint8Array([240, 159, 152, 138]))
'😊'
```

Does it answer your question?

**Comment by silverbullettruck2001** [comment]
I'm just using pure JS.  I have been doing the `new TextDecoder...` but I was just curious if there was a way to make it default to decode.  Maybe add another property that decodes it using the specified decoder function just to make it easier to consume and easier to debug?  If you added a property that contained the `decodedArgs` or something like that as well?

**Comment by iliabylich** [comment]
There's no guarantee that `Uint8Array` is a valid string, this is why original byte sequence is provided. And by having decoded array somewhere in the next property you can't know that it's valid (I think V8 replaces unknown chars with `?` placeholder), so that'd be an unreliable API.

**Comment by iliabylich** [comment]
Feel free to reopen if you still have questions.
